// Generated by gencpp from file lvtn_pkg/Coordinates.msg
// DO NOT EDIT!


#ifndef LVTN_PKG_MESSAGE_COORDINATES_H
#define LVTN_PKG_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lvtn_pkg
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : x(0)
    , y(0)
    , d(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef float _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::lvtn_pkg::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lvtn_pkg::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::lvtn_pkg::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::lvtn_pkg::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::lvtn_pkg::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lvtn_pkg::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lvtn_pkg::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lvtn_pkg::Coordinates_<ContainerAllocator1> & lhs, const ::lvtn_pkg::Coordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lvtn_pkg::Coordinates_<ContainerAllocator1> & lhs, const ::lvtn_pkg::Coordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lvtn_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lvtn_pkg::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lvtn_pkg::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lvtn_pkg::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b79627109fef5e4034006638adf0655d";
  }

  static const char* value(const ::lvtn_pkg::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb79627109fef5e40ULL;
  static const uint64_t static_value2 = 0x34006638adf0655dULL;
};

template<class ContainerAllocator>
struct DataType< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lvtn_pkg/Coordinates";
  }

  static const char* value(const ::lvtn_pkg::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
"float32 d\n"
;
  }

  static const char* value(const ::lvtn_pkg::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lvtn_pkg::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lvtn_pkg::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LVTN_PKG_MESSAGE_COORDINATES_H
